export const coreAbbreviations = {
  S: "Strength",
  D: "Dexterity",
  C: "Constitution",
  I: "Intelligence",
  W: "Wisdom",
  Ch: "Charisma",
  WP: "Willpower",
  SP: "Spirit",
  A: "Arcane",
  P: "Presence",
};

export const skillAbbreviations = {
  // Strength skills
  as: "Anchor Stance",
  gs: "Grip Strength",
  bwf: "Bodyweight Force",
  bf: "Brute Force",
  chg: "Charge",
  cl: "Climb",
  fc: "Fist Conditioning",
  gp: "Grappling",
  he: "Heavy Endurance",
  ir: "Impact Resistance",
  ig: "Iron Grip",
  lf: "Lifting Form",
  lb: "Load Bearing",
  ls: "Load Stabilization",
  mm: "Momentum Management",
  mc: "Muscle Control",
  ofa: "Opposing Force Application",
  ohs: "Overhead Strength",
  ps: "Postural Strength",
  pl: "Power Lift",
  sa: "Shock Absorption",
  ss: "Shoulder Strength",
  sts: "Stone Stance",
  wpn: "Weapon Mastery",
  wt: "Weight Toss",

  // Dexterity skills
  ac: "Acrobatics",
  as2: "Aimed Shot",
  amb: "Ambidexterity",
  ms: "Missile Snaring",
  bl: "Balance",
  bp: "Blade Precision",
  cc: "Critical Chance",
  cd: "Critical Damage",
  dp: "Dual Precision",
  ea: "Escape Artist",
  ev: "Evasion",
  lp: "Lockpicking",
  pt: "Precision Throwing",
  qc: "Quick Draw",
  ra: "Reflex Training",
  sh: "Sleight of Hand",
  st: "Stealth",
  tc: "Throwing Combo",
  td: "Trigger Discipline",
  vp: "Vital Point Targeting",
  wf: "Weapon Finesse",
  wc: "Whip Control",

  // Constitution skills
  acr: "Acid Resistance",
  ad: "Adaptability",
  bc: "Blood Circulation",
  blr: "Bludgeoning Resistance",
  brc: "Breath Control",
  cr: "Cold Resistance",
  cs: "Core Strength",
  dr: "Disease Resistance",
  end: "Endurance",
  fs: "Fat Storage",
  fr: "Fire Resistance",
  for: "Force Resistance",
  fr2: "Frost Resistance",
  hr: "Heat Resistance",
  ht: "Hunger Tolerance",
  lr: "Lightning Resistance",
  lon: "Longevity",
  nh: "Natural Healing",
  pt2: "Pain Tolerance",
  pp: "Physical Perseverance",
  pier: "Piercing Resistance",
  poisr: "Poison Resistance",
  rb: "Recovery Boost",
  sr2: "Shock Resistance",
  slr: "Slashing Resistance",
  se: "Sleep Efficiency",
  sr3: "Stamina Recovery",
  strr: "Stress Resistance",
  thr: "Thunder Resistance",
  togh: "Toughness",
  toxr: "Toxin Resistance",
  vit: "Vitality",

  // Intelligence skills
  arc: "Arcana",
  cb: "Codebreaking",
  ca: "Cognitive Adaptability",
  eng: "Engineering",
  his: "History",
  ila: "Illusion Analysis",
  inv: "Investigation",
  ks: "Knowledge Synthesis",
  ling: "Linguistics",
  log: "Logic",
  mt: "Magical Theory",
  math: "Mathematics",
  mr: "Memory Recall",
  mf: "Mental Fortitude",
  mir: "Mind Resistance",
  ok: "Occult Knowledge",
  pd: "Psychic Defense",
  rs: "Religious Studies",
  sf: "Strategic Foresight",
  tp: "Tactical Planning",

  // Wisdom skills
  al: "Absorptive Listening",
  caw: "Caution Awareness",
  cde: "Conflict De-escalation",
  cth: "Consequential Thinking",
  cp: "Crisis Perception",
  cf: "Cultural Fluency",
  er: "Experience Recall",
  ft: "Foresight Temperance",
  gi: "Guidance Instinct",
  ins: "Insight",
  ib: "Interpersonal Balance",
  ig: "Introspective Growth",
  lrn: "Lesson Retention",
  ma: "Memory Anchoring",
  maw: "Mentorship Awareness",
  md: "Moral Discernment",
  ol: "Observation Logging",
  pd2: "Patience Discipline",
  pr: "Pattern Recognition",
  pj: "Practical Judgment",
  sa: "Situational Awareness",
  si: "Spiritual Intuition",
  wr: "Wisdom Reception",

  // Charisma skills
  ap: "Ambassadorial Presence",
  ar: "Audience Reading",
  bo: "Boast",
  ch: "Charm",
  ce: "Courtly Etiquette",
  deb: "Debate",
  dec: "Deception",
  dip: "Diplomacy",
  dd: "Disguise Demeanor",
  fi: "Feign Innocence",
  fl: "Flattery",
  gm: "Gossip Management",
  hag: "Haggle",
  ic: "Inspire Courage",
  int: "Intimidation",
  lead: "Leadership",
  ld: "Lie Detection",
  mi: "Magical Influence",
  md2: "Mock Duel",
  ora: "Oratory",
  perf: "Performance",
  pers: "Persuasion",
  ps: "Public Speaking",
  rt: "Rally Troops",
  rr: "Read the Room",
  sed: "Seduction",
  st2: "Smooth Talk",
  sr2: "Soul Resonance",
  sp: "Stage Presence",
  sw: "Storyweaving",
};
