const { db } = require("./firebase"); // ✅ pulls db from firebase.js
const {
  defineAllTier1Skills,
} = require("../frontend/mystical/Arcane/tiers/tier_1/tier_1_index.js");

const fullTemplate = {
  meta: {
    character_id: "",
    level: 0,
  },
  primary_scores: {
    Strength: 1,
    Dexterity: 1,
    Constitution: 1,
    Intelligence: 1,
    Wisdom: 1,
    Charisma: 1,
  },
  secondary_scores: {
    Willpower: 0,
    Spirit: 0,
    Arcane: 0,
    Presence: 0,
  },
  skills: {
    Strength: {
      "Anchor Stance": {
        description:
          "Plant yourself solidly to resist being pushed or knocked down. [(H)Armor+]",
        boost: ["armor:heavy"],
        effective_value: 0,
      },
      "Grip Strength": {
        description:
          "Hold and carry heavy objects with powerful hand and forearm muscles. [(R)PhysDmg+]",
        boost: ["damage:raw"],
        effective_value: 0,
      },
      "Bodyweight Force": {
        description:
          "Utilize your own body weight to maximize pushing or pulling power. [(M/R)Dmg+, (M)Acc+]",
        boost: ["damage:raw", "melee:accuracy"],
        effective_value: 0,
      },
      "Brute Force": {
        description:
          "Apply overwhelming strength to break through obstacles. [(M/R)Dmg+, (M)Acc+]",
        boost: ["damage:raw", "melee:accuracy"],
        effective_value: 0,
      },
      Charge: {
        description:
          "Dash with great momentum to knock over foes or barriers. [(M/R)Dmg+, (M)Acc+]",
        boost: ["damage:raw", "melee:accuracy"],
        effective_value: 0,
      },
      Climb: {
        description:
          "Ascend difficult surfaces using sheer physical force and endurance.",
        boost: [],
        effective_value: 0,
      },
      "Fist Conditioning": {
        description:
          "Condition your fists to withstand impact and deliver more powerful strikes. [(R)PhysDmg+, (M)Acc+]",
        boost: ["damage:raw", "melee:accuracy"],
        effective_value: 0,
      },
      Grappling: {
        description:
          "Engage in hand-to-hand combat focusing on holds, throws, and immobilization. [(M)Acc+]",
        boost: ["melee:accuracy"],
        effective_value: 0,
      },
      "Heavy Endurance": {
        description:
          "Carry heavy loads or wear heavy armor without fatigue. [(H)Armor+]",
        boost: ["armor:heavy"],
        effective_value: 0,
      },
      "Impact Resistance": {
        description:
          "Withstand physical impacts with minimal damage. [(H)Armor+]",
        boost: ["armor:heavy"],
        effective_value: 0,
      },
      "Iron Grip": {
        description:
          "Grasp objects or enemies so tightly they cannot escape. [(R)PhysDmg+]",
        boost: ["damage:raw"],
        effective_value: 0,
      },
      "Lifting Form": {
        description: "Lift objects efficiently using optimal body mechanics.",
        boost: [],
        effective_value: 0,
      },
      "Load Bearing": {
        description:
          "Carry loads across distances without hindering movement. [(R)PhysDmg+]",
        boost: ["damage:raw"],
        effective_value: 0,
      },
      "Load Stabilization": {
        description:
          "Balance and stabilize heavy objects while carrying. [(Ranged)Dmg+]",
        boost: ["damage:ranged"],
        effective_value: 0,
      },
      "Momentum Management": {
        description:
          "Control and harness the momentum generated by movement. [(M/R)Dmg+]",
        boost: ["damage:raw"],
        effective_value: 0,
      },
      "Muscle Control": {
        description:
          "Flex and control individual muscle groups to optimize strength output. [(M/R)Dmg+, (H)Armor+]",
        boost: ["damage:raw", "armor:heavy"],
        effective_value: 0,
      },
      "Opposing Force Application": {
        description:
          "Apply strength tactically to counter or redirect an opponent's force.",
        boost: [],
        effective_value: 0,
      },
      "Overhead Strength": {
        description:
          "Lift, throw, or support heavy objects above your head. [(Ranged)Dmg+]",
        boost: ["damage:ranged"],
        effective_value: 0,
      },
      "Postural Strength": {
        description:
          "Maintain strong posture and balance under physical stress. [(H)Armor+]",
        boost: ["armor:heavy"],
        effective_value: 0,
      },
      "Power Lift": {
        description:
          "Exert great force to lift or hold heavy objects with minimal strain. [(Ranged)Dmg+, (H)Armor+]",
        boost: ["damage:ranged", "armor:heavy"],
        effective_value: 0,
      },
      "Shock Absorption": {
        description:
          "Minimize internal damage when subjected to heavy impacts.",
        boost: [],
        effective_value: 0,
      },
      "Shoulder Strength": {
        description:
          "Strengthen shoulder muscles for greater reach and leverage. [(R/M)Dmg+, (H)Armor+]",
        boost: ["damage:raw", "armor:heavy"],
        effective_value: 0,
      },
      "Stone Stance": {
        description:
          "Become immovable once you plant your feet firmly. [(H)Armor+]",
        boost: ["armor:heavy"],
        effective_value: 0,
      },
      "Weapon Mastery": {
        description:
          "Handle large melee weapons with strength and control. [(M)Dmg+, (M/R)Acc+]",
        boost: ["damage:melee", "melee:accuracy", "ranged:accuracy"],
        effective_value: 0,
      },
      "Weight Toss": {
        description:
          "Throw heavy objects accurately and forcefully. [(Ranged)Dmg+]",
        boost: ["damage:ranged"],
        effective_value: 0,
      },
    },

    Dexterity: {
      Acrobatics: {
        description:
          "Perform flips, rolls, and agile maneuvers with grace. [(M)Acc+, (Move)Speed+, (H)Armor+]",
        boost: ["melee:accuracy", "move:speed", "armor:heavy"],
        effective_value: 0,
      },
      "Aimed Shot": {
        description:
          "Precisely fire or throw projectiles at distant or moving targets. [(Ranged)Acc+]",
        boost: ["ranged:accuracy"],
        effective_value: 0,
      },
      Ambidexterity: {
        description:
          "Use both hands with equal proficiency for tasks or combat. [(M)Acc+, (H)Armor+]",
        boost: ["melee:accuracy", "armor:heavy"],
        effective_value: 0,
      },
      "Missile Snaring": {
        description:
          "Catch incoming projectiles with swift movements. [(H)Armor+]",
        boost: ["armor:heavy"],
        effective_value: 0,
      },
      Balance: {
        description:
          "Maintain footing on unstable, narrow, or hazardous surfaces. [(H)Armor+]",
        boost: ["armor:heavy"],
        effective_value: 0,
      },
      "Blade Precision": {
        description:
          "Strike with pinpoint accuracy using bladed weapons. [(M)Dmg+, (M)Acc+]",
        boost: ["damage:melee", "melee:accuracy"],
        effective_value: 0,
      },
      "Critical Chance": {
        description: "Increase the likelihood of delivering critical strikes.",
        boost: [],
        effective_value: 0,
      },
      "Critical Damage": {
        description:
          "Enhance the power of critical hits when they occur. [(Crit)Dmg+]",
        boost: ["combat:crit_damage"],
        effective_value: 0,
      },
      "Dual Precision": {
        description:
          "Wield two weapons with synchronized precision and timing.",
        boost: [],
        effective_value: 0,
      },
      "Escape Artist": {
        description: "Slip free from bindings, grapples, or tight spaces.",
        boost: [],
        effective_value: 0,
      },
      Evasion: {
        description:
          "Dodge attacks and avoid area effects with fluid movements. [(Move)Speed+, (H)Armor+]",
        boost: ["move:speed", "armor:heavy"],
        effective_value: 0,
      },
      Lockpicking: {
        description: "Bypass locks and secured doors using fine manual skills.",
        boost: [],
        effective_value: 0,
      },
      "Precision Throwing": {
        description:
          "Throw objects or weapons with surgical precision. [(Ranged)Dmg+, (Ranged)Acc+]",
        boost: ["damage:ranged", "ranged:accuracy"],
        effective_value: 0,
      },
      "Quick Draw": {
        description:
          "Rapidly draw weapons to gain advantage in combat. [(M/R)Acc+, (H)Armor+]",
        boost: ["melee:accuracy", "ranged:accuracy", "armor:heavy"],
        effective_value: 0,
      },
      "Reflex Training": {
        description:
          "React faster to threats and stimuli in your environment. [(M)Acc+, (Move)Speed+, (H)Armor+]",
        boost: ["melee:accuracy", "move:speed", "armor:heavy"],
        effective_value: 0,
      },
      "Sleight of Hand": {
        description:
          "Manipulate objects discreetly for magic tricks, theft, or escape. [(M)Acc+]",
        boost: ["melee:accuracy"],
        effective_value: 0,
      },
      Stealth: {
        description: "Move silently and avoid detection from enemies.",
        boost: [],
        effective_value: 0,
      },
      "Throwing Combo": {
        description:
          "Chain multiple thrown attacks together for maximum effect.",
        boost: [],
        effective_value: 0,
      },
      "Trigger Discipline": {
        description:
          "Improve accuracy and safety when using firearms or ranged tools. [(Ranged)Acc+]",
        boost: ["ranged:accuracy"],
        effective_value: 0,
      },
      "Vital Point Targeting": {
        description:
          "Strike weak points to disable enemies swiftly. [(M/R)Acc+, (Crit)Dmg+]",
        boost: ["melee:accuracy", "ranged:accuracy", "combat:crit_damage"],
        effective_value: 0,
      },
      "Weapon Finesse": {
        description:
          "Apply agility instead of strength to attacks with light weapons. [(M)Dmg+, (M)Acc+, (H)Armor+]",
        boost: ["damage:melee", "melee:accuracy", "armor:heavy"],
        effective_value: 0,
      },
      "Whip Control": {
        description: "Master flexible weapons such as whips or chains.",
        boost: [],
        effective_value: 0,
      },
    },

    Constitution: {
      "Acid Resistance": {
        description: "Reduce the effects of corrosive substances.",
        boost: [],
        effective_value: 0,
      },
      Adaptability: {
        description:
          "Adjust to harsh environments and unexpected challenges more easily. [(H)Armor+]",
        boost: ["armor:heavy"],
        effective_value: 0,
      },
      "Blood Circulation": {
        description:
          "Maintain consistent body performance under stress. [(H)Health+]",
        boost: ["health:max"],
        effective_value: 0,
      },
      "Bludgeoning Resistance": {
        description: "Reduce damage from blunt weapons or impacts. [(H)Armor+]",
        boost: ["armor:heavy"],
        effective_value: 0,
      },
      "Breath Control": {
        description:
          "Hold breath for long durations or function in low-oxygen environments.",
        boost: [],
        effective_value: 0,
      },
      "Cold Resistance": {
        description: "Withstand freezing temperatures and harsh climates.",
        boost: [],
        effective_value: 0,
      },
      "Core Strength": {
        description:
          "Improve internal body strength and stability. [(H)Health+, (H)Armor+]",
        boost: ["health:max", "armor:heavy"],
        effective_value: 0,
      },
      "Disease Resistance": {
        description: "Natural resilience against infections and illnesses.",
        boost: [],
        effective_value: 0,
      },
      Endurance: {
        description:
          "Sustain physical activity over extended periods without fatigue. [(H)Health+]",
        boost: ["health:max"],
        effective_value: 0,
      },
      "Fat Storage": {
        description: "Efficiently manage bodily energy reserves. [(H)Health+]",
        boost: ["health:max"],
        effective_value: 0,
      },
      "Fire Resistance": {
        description: "Reduce or negate damage from fire-based attacks.",
        boost: [],
        effective_value: 0,
      },
      "Force Resistance": {
        description: "Resist magical or concussive force effects.",
        boost: [],
        effective_value: 0,
      },
      "Frost Resistance": {
        description: "Minimize harm from freezing or icy conditions.",
        boost: [],
        effective_value: 0,
      },
      "Heat Resistance": {
        description: "Endure extreme heat and dehydration.",
        boost: [],
        effective_value: 0,
      },
      "Hunger Tolerance": {
        description: "Function effectively with minimal food intake.",
        boost: [],
        effective_value: 0,
      },
      "Lightning Resistance": {
        description: "Deflect or ground electrical damage sources.",
        boost: [],
        effective_value: 0,
      },
      Longevity: {
        description:
          "Extend life expectancy and reduce aging effects. [(H)Health+]",
        boost: ["health:max"],
        effective_value: 0,
      },
      "Natural Healing": {
        description:
          "Regenerate from wounds and recover health over time. [(H)Health+]",
        boost: ["health:max"],
        effective_value: 0,
      },
      "Pain Tolerance": {
        description:
          "Resist pain from injury or strenuous exertion. [(H)Health+]",
        boost: ["health:max"],
        effective_value: 0,
      },
      "Physical Perseverance": {
        description:
          "Push through intense physical strain to complete difficult tasks. [(H)Health+, (H)Armor+, (Move)Speed+]",
        boost: ["health:max", "armor:heavy", "move:speed"],
        effective_value: 0,
      },
      "Piercing Resistance": {
        description:
          "Withstand stabs and punctures from sharp objects. [(H)Armor+]",
        boost: ["armor:heavy"],
        effective_value: 0,
      },
      "Poison Resistance": {
        description: "Mitigate damage and effects from toxins.",
        boost: [],
        effective_value: 0,
      },
      "Recovery Boost": {
        description: "Accelerate physical healing from injuries.",
        boost: [],
        effective_value: 0,
      },
      "Shock Resistance": {
        description: "Survive trauma from blunt force or energy-based attacks.",
        boost: [],
        effective_value: 0,
      },
      "Slashing Resistance": {
        description:
          "Deflect or reduce injury from cutting attacks. [(H)Armor+]",
        boost: ["armor:heavy"],
        effective_value: 0,
      },
      "Sleep Efficiency": {
        description: "Require less sleep while maintaining full performance.",
        boost: [],
        effective_value: 0,
      },
      "Stamina Recovery": {
        description: "Recover quickly from exhaustion or fatigue.",
        boost: [],
        effective_value: 0,
      },
      "Stress Resistance": {
        description: "Perform well under high-pressure situations.",
        boost: [],
        effective_value: 0,
      },
      "Thunder Resistance": {
        description: "Endure damage from forceful sound or vibrations.",
        boost: [],
        effective_value: 0,
      },
      Toughness: {
        description:
          "Reduce the severity of injuries taken. [(H)Health+, (H)Armor+]",
        boost: ["health:max", "armor:heavy"],
        effective_value: 0,
      },
      "Toxin Resistance": {
        description: "Withstand poisons and harmful substances.",
        boost: [],
        effective_value: 0,
      },
      Vitality: {
        description:
          "Enhance overall physical robustness and health. [(H)Health+]",
        boost: ["health:max"],
        effective_value: 0,
      },
    },

    Intelligence: {
      Arcana: {
        description:
          "Recall knowledge related to magic, spells, and mystical traditions. [(Energy)Acc+, (R)PhysDmg+]",
        boost: ["energy:accuracy", "damage:raw"],
        effective_value: 0,
      },
      Codebreaking: {
        description:
          "Decipher encrypted messages, hidden languages, and secret codes.",
        boost: [],
        effective_value: 0,
      },
      "Cognitive Adaptability": {
        description:
          "Quickly shift mental focus to solve new or changing problems.",
        boost: [],
        effective_value: 0,
      },
      Engineering: {
        description:
          "Apply scientific principles to design structures, machines, and tools.",
        boost: [],
        effective_value: 0,
      },
      History: {
        description:
          "Recall important historical events, cultures, and legendary figures.",
        boost: [],
        effective_value: 0,
      },
      "Illusion Analysis": {
        description:
          "Recognize and mentally dismantle illusions and falsehoods.",
        boost: [],
        effective_value: 0,
      },
      Investigation: {
        description:
          "Search for hidden clues, inconsistencies, or small details others miss.",
        boost: [],
        effective_value: 0,
      },
      "Knowledge Synthesis": {
        description:
          "Combine disparate fields of knowledge into new theories or ideas.",
        boost: [],
        effective_value: 0,
      },
      Linguistics: {
        description: "Understand and learn new languages quickly and fluently.",
        boost: [],
        effective_value: 0,
      },
      Logic: {
        description:
          "Apply deductive reasoning to solve puzzles and uncover truths.",
        boost: [],
        effective_value: 0,
      },
      "Magical Theory": {
        description:
          "Comprehend the underlying mechanisms behind magical phenomena. [(Energy)Acc+, (R)PhysDmg+]",
        boost: ["energy:accuracy", "damage:raw"],
        effective_value: 0,
      },
      Mathematics: {
        description:
          "Perform advanced calculations and geometric problem-solving.",
        boost: [],
        effective_value: 0,
      },
      "Memory Recall": {
        description:
          "Retrieve specific memories with great clarity and detail.",
        boost: [],
        effective_value: 0,
      },
      "Mental Fortitude": {
        description:
          "Resist mental domination, psychic assault, and confusion effects.",
        boost: [],
        effective_value: 0,
      },
      "Mind Resistance": {
        description:
          "Protect your mind against mental intrusions and manipulation.",
        boost: [],
        effective_value: 0,
      },
      "Occult Knowledge": {
        description:
          "Understand esoteric and forbidden subjects beyond mortal ken. [(Energy)Acc+]",
        boost: ["energy:accuracy"],
        effective_value: 0,
      },
      "Psychic Defense": {
        description:
          "Form mental shields to block psychic and telepathic attacks.",
        boost: [],
        effective_value: 0,
      },
      "Religious Studies": {
        description:
          "Comprehend theology, divine orders, and mythological systems.",
        boost: [],
        effective_value: 0,
      },
      "Strategic Foresight": {
        description:
          "Predict enemy actions and devise effective countermeasures. [(M/R/E)Acc+, (R)PhysDmg+]",
        boost: [
          "melee:accuracy",
          "ranged:accuracy",
          "energy:accuracy",
          "damage:raw",
        ],
        effective_value: 0,
      },
      "Tactical Planning": {
        description:
          "Organize battlefield tactics and small-unit coordination. [(M/R/E)Acc+, (R)PhysDmg+]",
        boost: [
          "melee:accuracy",
          "ranged:accuracy",
          "energy:accuracy",
          "damage:raw",
        ],
        effective_value: 0,
      },
    },

    Wisdom: {
      "Absorptive Listening": {
        description:
          "Absorb spoken knowledge and stories with precision and understanding.",
        boost: [],
        effective_value: 0,
      },
      "Caution Awareness": {
        description: "Perceive dangers before they strike.",
        boost: [],
        effective_value: 0,
      },
      "Conflict De-escalation": {
        description:
          "Defuse hostile situations through insight and calm influence.",
        boost: [],
        effective_value: 0,
      },
      "Consequential Thinking": {
        description:
          "Predict outcomes based on observed behavior and decisions.",
        boost: [],
        effective_value: 0,
      },
      "Crisis Perception": {
        description: "Stay calm and process fast-moving danger effectively.",
        boost: [],
        effective_value: 0,
      },
      "Cultural Fluency": {
        description:
          "Understand cultural practices, customs, and expectations.",
        boost: [],
        effective_value: 0,
      },
      "Experience Recall": {
        description: "Draw on personal past experiences to make decisions.",
        boost: [],
        effective_value: 0,
      },
      "Foresight Temperance": {
        description: "Balance future planning with patience and timing.",
        boost: [],
        effective_value: 0,
      },
      "Guidance Instinct": {
        description:
          "Help others find purpose and direction through intuition.",
        boost: [],
        effective_value: 0,
      },
      Insight: {
        description:
          "Understand intentions and hidden truths through subtle cues. [(M/R/E)Acc+, (R)PhysDmg+]",
        boost: [
          "melee:accuracy",
          "ranged:accuracy",
          "energy:accuracy",
          "damage:raw",
        ],
        effective_value: 0,
      },
      "Interpersonal Balance": {
        description: "Maintain calm, respectful dynamics in conversations.",
        boost: [],
        effective_value: 0,
      },
      "Introspective Growth": {
        description:
          "Learn from past mistakes and evolve mentally and emotionally.",
        boost: [],
        effective_value: 0,
      },
      "Lesson Retention": {
        description: "Retain lessons learned through experience and study.",
        boost: [],
        effective_value: 0,
      },
      "Memory Anchoring": {
        description: "Tie memories to emotions and context for quick recall.",
        boost: [],
        effective_value: 0,
      },
      "Mentorship Awareness": {
        description: "Recognize the growth and needs of others over time.",
        boost: [],
        effective_value: 0,
      },
      "Moral Discernment": {
        description: "Sense ethical balance and right action instinctively.",
        boost: [],
        effective_value: 0,
      },
      "Observation Logging": {
        description:
          "Track and mentally record details from your surroundings. [(M/R/E)Acc+, (R)PhysDmg+]",
        boost: [
          "melee:accuracy",
          "ranged:accuracy",
          "energy:accuracy",
          "damage:raw",
        ],
        effective_value: 0,
      },
      "Patience Discipline": {
        description: "Remain focused and restrained when provoked.",
        boost: [],
        effective_value: 0,
      },
      "Pattern Recognition": {
        description:
          "Identify trends and repeated behaviors to anticipate outcomes.",
        boost: [],
        effective_value: 0,
      },
      "Practical Judgment": {
        description: "Choose realistic and effective responses under pressure.",
        boost: [],
        effective_value: 0,
      },
      "Situational Awareness": {
        description:
          "Constantly assess your environment for threats and openings. [(M/R/E)Acc+, (R)PhysDmg+]",
        boost: [
          "melee:accuracy",
          "ranged:accuracy",
          "energy:accuracy",
          "damage:raw",
        ],
        effective_value: 0,
      },
      "Spiritual Intuition": {
        description: "Sense spiritual forces and meanings beyond the material.",
        boost: [],
        effective_value: 0,
      },
      "Wisdom Reception": {
        description:
          "Take in teachings and advice without ego or defensiveness.",
        boost: [],
        effective_value: 0,
      },
    },

    Charisma: {
      "Ambassadorial Presence": {
        description:
          "Represent your group with authority and grace in foreign lands.",
        boost: [],
        effective_value: 0,
      },
      "Audience Reading": {
        description: "Gauge the reactions and moods of a crowd or listener.",
        boost: [],
        effective_value: 0,
      },
      Boast: {
        description: "Impress others with your accomplishments or bravado.",
        boost: [],
        effective_value: 0,
      },
      Charm: {
        description:
          "Influence others through likability and subtle persuasion.",
        boost: [],
        effective_value: 0,
      },
      "Courtly Etiquette": {
        description:
          "Navigate noble courts and aristocratic society with grace.",
        boost: [],
        effective_value: 0,
      },
      Debate: {
        description: "Argue logically and convincingly to sway opinions.",
        boost: [],
        effective_value: 0,
      },
      Deception: {
        description: "Convince others of falsehoods with confidence.",
        boost: [],
        effective_value: 0,
      },
      Diplomacy: {
        description: "Facilitate agreements and prevent conflict through tact.",
        boost: [],
        effective_value: 0,
      },
      "Disguise Demeanor": {
        description: "Adopt alternate identities and mannerisms seamlessly.",
        boost: [],
        effective_value: 0,
      },
      "Feign Innocence": {
        description: "Appear guiltless or harmless when accused.",
        boost: [],
        effective_value: 0,
      },
      Flattery: {
        description: "Compliment strategically to gain favor.",
        boost: [],
        effective_value: 0,
      },
      "Gossip Management": {
        description:
          "Control rumors and reputation through social maneuvering.",
        boost: [],
        effective_value: 0,
      },
      Haggle: {
        description: "Negotiate prices and terms in your favor.",
        boost: [],
        effective_value: 0,
      },
      "Inspire Courage": {
        description: "Rally others with words of bravery and resolve.",
        boost: [],
        effective_value: 0,
      },
      Intimidation: {
        description: "Use fear to assert dominance or compel behavior.",
        boost: [],
        effective_value: 0,
      },
      Leadership: {
        description:
          "Command respect and inspire loyalty through action and presence.",
        boost: [],
        effective_value: 0,
      },
      "Lie Detection": {
        description: "Sense dishonesty in others through behavioral cues.",
        boost: [],
        effective_value: 0,
      },
      "Magical Influence": {
        description: "Bend magical forces through charisma and willpower.",
        boost: [],
        effective_value: 0,
      },
      "Mock Duel": {
        description: "Engage in playful combat to prove dominance socially.",
        boost: [],
        effective_value: 0,
      },
      Oratory: {
        description: "Deliver formal speeches that inform or inspire.",
        boost: [],
        effective_value: 0,
      },
      Performance: {
        description: "Captivate an audience through music, acting, or dance.",
        boost: [],
        effective_value: 0,
      },
      Persuasion: {
        description: "Convince others to accept your ideas or proposals.",
        boost: [],
        effective_value: 0,
      },
      "Public Speaking": {
        description: "Speak confidently and clearly before groups.",
        boost: [],
        effective_value: 0,
      },
      "Rally Troops": {
        description: "Inspire fighters to press on with renewed vigor.",
        boost: [],
        effective_value: 0,
      },
      "Read the Room": {
        description:
          "Discern unspoken tension, moods, and dynamics in a group.",
        boost: [],
        effective_value: 0,
      },
      Seduction: {
        description: "Use charm and allure to achieve personal goals.",
        boost: [],
        effective_value: 0,
      },
      "Smooth Talk": {
        description: "Get out of trouble or persuade without facts.",
        boost: [],
        effective_value: 0,
      },
      "Soul Resonance": {
        description:
          "Align emotionally and spiritually with another’s essence.",
        boost: [],
        effective_value: 0,
      },
      "Stage Presence": {
        description: "Own the space around you and demand attention.",
        boost: [],
        effective_value: 0,
      },
      Storyweaving: {
        description: "Tell compelling tales that inform, persuade, or mystify.",
        boost: [],
        effective_value: 0,
      },
    },

    Willpower: {},

    Spirit: {},

    Arcane: {}, // defineAllTier1Skills function does this

    Presence: {},
  },
};

db.ref("template")
  .set(fullTemplate)
  .then(() => {
    console.log("✅ Template uploaded to Firebase.");
    defineAllTier1Skills(db);
  })
  .catch((error) => console.error("❌ Failed to upload:", error));
