// Active strength skills organized in tiers
export const strengthActiveSkills = {
  "Tier 1": {
    "Grip Strength": {
      description:
        "Hold and carry heavy objects with powerful hand and forearm muscles.",
      prerequisites: [],
      boost: ["damage:raw"],
      effective_value: 0,
    },
    "Muscle Control": {
      description:
        "Fine-tune muscle activation for precise strength application.",
      prerequisites: [{ skill: "Grip Strength", minLevel: 3 }],
      boost: ["melee:accuracy"],
      effective_value: 0,
    },
    "Load Bearing": {
      description: "Carry loads across distances without hindering movement.",
      prerequisites: [{ skill: "Muscle Control", minLevel: 3 }],
      boost: ["damage:raw"],
      effective_value: 0,
    },
    "Postural Strength": {
      description: "Maintain strong posture and balance under physical stress.",
      prerequisites: [{ skill: "Load Bearing", minLevel: 3 }],
      boost: ["armor:heavy"],
      effective_value: 0,
    },
    "Core Foundation": {
      description:
        "Develop core stability for improved power transfer and balance.",
      prerequisites: [{ skill: "Postural Strength", minLevel: 3 }],
      boost: ["armor:heavy", "melee:accuracy"],
      effective_value: 0,
    },
  },
  "Tier 2": {
    "Fist Conditioning": {
      description:
        "Condition your fists to withstand impact and deliver more powerful strikes.",
      prerequisites: [
        { skill: "Core Foundation", minLevel: 3, requiredRank: "E" },
      ],
      boost: ["damage:raw", "melee:accuracy"],
      effective_value: 0,
    },
    "Bodyweight Force": {
      description:
        "Utilize your own body weight to maximize pushing or pulling power.",
      prerequisites: [{ skill: "Fist Conditioning", minLevel: 3 }],
      boost: ["damage:raw", "melee:accuracy"],
      effective_value: 0,
    },
    "Load Stabilization": {
      description: "Balance and stabilize heavy objects while carrying.",
      prerequisites: [{ skill: "Bodyweight Force", minLevel: 3 }],
      boost: ["damage:ranged"],
      effective_value: 0,
    },
    "Shoulder Strength": {
      description:
        "Strengthen shoulder muscles for greater reach and leverage.",
      prerequisites: [{ skill: "Load Stabilization", minLevel: 3 }],
      boost: ["damage:raw", "armor:heavy"],
      effective_value: 0,
    },
    "Momentum Management": {
      description: "Control and harness the momentum generated by movement.",
      prerequisites: [{ skill: "Shoulder Strength", minLevel: 3 }],
      boost: ["damage:raw"],
      effective_value: 0,
    },
  },
  "Tier 3": {
    "Brute Force": {
      description: "Apply overwhelming strength to break through obstacles.",
      prerequisites: [
        { skill: "Momentum Management", minLevel: 3, requiredRank: "D" },
      ],
      boost: ["damage:raw", "melee:accuracy"],
      effective_value: 0,
    },
    Grappling: {
      description:
        "Engage in hand-to-hand combat focusing on holds, throws, and immobilization.",
      prerequisites: [{ skill: "Brute Force", minLevel: 3 }],
      boost: ["melee:accuracy"],
      effective_value: 0,
    },
    "Heavy Endurance": {
      description: "Carry heavy loads or wear heavy armor without fatigue.",
      prerequisites: [{ skill: "Grappling", minLevel: 3 }],
      boost: ["armor:heavy"],
      effective_value: 0,
    },
    "Iron Grip": {
      description: "Grasp objects or enemies so tightly they cannot escape.",
      prerequisites: [{ skill: "Heavy Endurance", minLevel: 3 }],
      boost: ["damage:raw"],
      effective_value: 0,
    },
    "Overhead Strength": {
      description: "Lift, throw, or support heavy objects above your head.",
      prerequisites: [{ skill: "Iron Grip", minLevel: 3 }],
      boost: ["damage:ranged"],
      effective_value: 0,
    },
  },
  "Tier 4": {
    "Weapon Mastery": {
      description: "Handle large melee weapons with strength and control.",
      prerequisites: [
        { skill: "Overhead Strength", minLevel: 3, requiredRank: "B" },
      ],
      boost: ["damage:melee", "melee:accuracy", "ranged:accuracy"],
      effective_value: 0,
    },
    "Weight Toss": {
      description: "Throw heavy objects accurately and forcefully.",
      prerequisites: [{ skill: "Weapon Mastery", minLevel: 3 }],
      boost: ["damage:ranged"],
      effective_value: 0,
    },
    Charge: {
      description: "Dash with great momentum to knock over foes or barriers.",
      prerequisites: [{ skill: "Weight Toss", minLevel: 3 }],
      boost: ["damage:raw", "melee:accuracy"],
      effective_value: 0,
    },
    "Impact Resistance": {
      description: "Withstand physical impacts with minimal damage.",
      prerequisites: [{ skill: "Charge", minLevel: 3 }],
      boost: ["armor:heavy"],
      effective_value: 0,
    },
    "Anchor Stance": {
      description:
        "Plant yourself solidly to resist being pushed or knocked down.",
      prerequisites: [{ skill: "Impact Resistance", minLevel: 3 }],
      boost: ["armor:heavy"],
      effective_value: 0,
    },
  },
  "Tier 5": {
    "Mountain's Strength": {
      description: "Become an immovable object and an unstoppable force.",
      prerequisites: [
        { skill: "Anchor Stance", minLevel: 3, requiredRank: "A" },
      ],
      boost: ["damage:raw", "armor:heavy"],
      effective_value: 0,
    },
    "Earth Shaker": {
      description:
        "Your powerful strikes can create shockwaves through the ground.",
      prerequisites: [{ skill: "Mountain's Strength", minLevel: 3 }],
      boost: ["damage:raw", "melee:accuracy"],
      effective_value: 0,
    },
    "Power Lift": {
      description:
        "Exert great force to lift or hold heavy objects with minimal strain.",
      prerequisites: [{ skill: "Earth Shaker", minLevel: 3 }],
      boost: ["damage:ranged", "armor:heavy"],
      effective_value: 0,
    },
    "Crushing Grip": {
      description:
        "Apply devastating pressure with your enhanced grip strength.",
      prerequisites: [{ skill: "Power Lift", minLevel: 3 }],
      boost: ["damage:raw"],
      effective_value: 0,
    },
  },
  "Final Tier": {
    "Titan's Legacy": {
      description:
        "Your strength reaches mythical proportions, inspiring legends.",
      prerequisites: [
        { skill: "Crushing Grip", minLevel: 3, requiredRank: "S" },
      ],
      boost: ["damage:raw", "melee:accuracy", "armor:heavy"],
      effective_value: 0,
    },
    "World Breaker": {
      description: "Your strikes can reshape the battlefield itself.",
      prerequisites: [{ skill: "Titan's Legacy", minLevel: 3 }],
      boost: ["damage:raw", "melee:accuracy", "armor:heavy"],
      effective_value: 0,
    },
    "Strength Incarnate": {
      description: "You become a living embodiment of pure physical might.",
      prerequisites: [{ skill: "World Breaker", minLevel: 3 }],
      boost: ["damage:raw", "melee:accuracy", "armor:heavy"],
      effective_value: 0,
    },
  },
};
